### ISSUE TITLE
[wiki] How to run on own dataset?

### ISSUE THREAD

**Issue by mahimairaja** [MiraPurkrabek/RePoGen#4]

**Comment by MiraPurkrabek** [comment]
Hello @mahimairaja ,
I appreciate your interest in our work. The proposed method is for generating synthetic data, which are then used to augment the existing dataset. If you want to test our approach on some top- or bottom-view data, I recommend using the ViTPose repository ([link](https://github.com/ViTAE-Transformer/ViTPose)) along with weights trained on COCO and our synthetic data. The links to the weights are in the README and are for the ViTPose-S with the classic decoder. 
If you want to improve another model on extreme views and/or rare poses, add our synthetic data to the existing dataset and re-train the model yourself.

Hope this helps!

**Comment by YongtaoGe** [comment]
Hi, there.  @MiraPurkrabek Thanks for your great work. Could you give a brief explanation that how to get a COCO-format annotation from an smplx representation? I think smplx does not provide such regressor to do this.

**Comment by MiraPurkrabek** [comment]
Hi @YongtaoGe ,

You are right, the SMPLX model does not provide such a script. However, it provides you with 3D coordinates of 27 pre-defined joints. In the code, we generate the annotation in the following steps:
1. For each joint, define its neighborhood. The size of the neighborhood is fixed, selected manually such that at least one pixel of the neighborhood is always visible when the joint is not occluded 
2. Computer visibility of the neighborhoods. It is computed by the ray projection method from known 3D coordinates of the vertices.
3. If at least one vertex from the neighborhood is visible, mark the joint as visible. Otherwise it is unannotated (x=0, y=0, v=0) in the COCO format.

The main caveat is that there are no points annotated as "invisible" (v=1) as it's not clear how human annotators mark them.

Since our method also produces segmentation masks, the bounding box is defined by the segmentation mask.

The above described procedure is already implemented in the code so you can use it as is. If you want to use the synthetic data directly and not generate them yourself, you can re-use our synthetic dataset published on the [project website](MiraPurkrabek.github.io/RePoGen-paper).

**Comment by YongtaoGe** [comment]
@MiraPurkrabek Thanks for your reply. It helps a lot.

**Comment by MiraPurkrabek** [comment]
Closing the issue as it seems resolved. If you have any problems, feel free to re-open it.
