### ISSUE TITLE
Empty Backgrounds folder

### ISSUE THREAD

**Issue by jackie-vifive** [MiraPurkrabek/RePoGen#6]
Hello,

Thank you for this inspiring work on improving pose estimation accuracies.
When running the `sample_random_poses.py `script, I get a `FileNotFoundError` triggered by an empty `images/background `directory.

`FileNotFoundError: [Errno 2] No such file or directory: 'images/backgrounds'
`
From the literature, it seems that we intend to use commonly observed random backgrounds. Is this intended to be empty, and should I include random background my self? Or is there a reference to how the author has generated and incorporated random background images?

Thank you in advance!

**Comment by MiraPurkrabek** [comment]
Hello,

Thank you for the question. We downloaded random images from the Google search. Because of that, we do not have permission to share them publicly. 

I advise you to do the same - just search for specific backgrounds characteristic for scenes with people (rooms, streets, gyms and sports halls...). Our findings suggest that the background does not depend that much if it's not a uniform color and **if there are no people in the image**. This can cause severe problems.

Regarding the number - something between 10 and 30 should be OK unless you plan to generate vast amounts of data.

Hope this helps.
